name: firestore_cache
description: A Flutter plugin for fetching Firestore documents with read from
  cache first then server.
version: 2.3.0+1
homepage: https://github.com/zeshuaro/firestore_cache

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  cloud_firestore: ^5.0.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
